-- Insert courses from courses.txt
-- This migration adds all course data to the courses table

-- Insert all courses
INSERT INTO public.courses (title, description, price, duration, level, category, image_url, is_active) VALUES ('Website Development Diploma', 'Learn the fundamentals of website development with HTML, CSS, and JavaScript.', 4800, '3 Months', 'beginner', 'web', 'https://images.unsplash.com/photo-1529101091764-c3526daf38fe', true);
INSERT INTO public.courses (title, description, price, duration, level, category, image_url, is_active) VALUES ('Website Development Advance Diploma', 'Advanced website development with modern frameworks and tools.', 7800, '5 Months', 'advanced', 'web', 'https://images.unsplash.com/photo-1581090700227-4c4f50b6b3d3', true);
INSERT INTO public.courses (title, description, price, duration, level, category, image_url, is_active) VALUES ('Digital Marketing Diploma', 'Master SEO, social media marketing, and digital strategies.', 11800, '5 Months', 'intermediate', 'marketing', 'https://images.unsplash.com/photo-1508830524289-0adcbe822b40', true);
INSERT INTO public.courses (title, description, price, duration, level, category, image_url, is_active) VALUES ('Computer Basic', 'Get started with basic computer knowledge and essential applications.', 3000, '3 Months', 'beginner', 'computer', 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8', true);
INSERT INTO public.courses (title, description, price, duration, level, category, image_url, is_active) VALUES ('Computer Advance', 'Advance your computer skills with operating systems and office automation.', 4000, '6 Months', 'advanced', 'computer', 'https://images.unsplash.com/photo-1518770660439-4636190af475', true);
INSERT INTO public.courses (title, description, price, duration, level, category, image_url, is_active) VALUES ('Computer Master', 'Comprehensive mastery of computer operations and applications.', 6000, '12 Months', 'advanced', 'computer', 'https://images.unsplash.com/photo-1555949963-aa79dcee981c', true);
INSERT INTO public.courses (title, description, price, duration, level, category, image_url, is_active) VALUES ('Graphic Design', 'Learn to design with modern tools and creative skills.', 4800, '3 Months', 'beginner', 'design', 'https://images.unsplash.com/photo-1508923567004-3a6b8004f3d3', true);
INSERT INTO public.courses (title, description, price, duration, level, category, image_url, is_active) VALUES ('Java Core', 'Learn the fundamentals of Java programming language.', 4800, '3 Months', 'intermediate', 'programming', 'https://images.unsplash.com/photo-1581091215367-59ab6a7c9f1d', true);
INSERT INTO public.courses (title, description, price, duration, level, category, image_url, is_active) VALUES ('Python Core', 'Learn the core concepts of Python programming for beginners.', 4800, '3 Months', 'intermediate', 'programming', 'https://images.unsplash.com/photo-1584697964190-ef9a7c8f1f6f', true);
INSERT INTO public.courses (title, description, price, duration, level, category, image_url, is_active) VALUES ('C Language', 'Understand the basics of programming with the C language.', 4800, '3 Months', 'beginner', 'programming', 'https://images.unsplash.com/photo-1518770660439-4636190af475', true);
INSERT INTO public.courses (title, description, price, duration, level, category, image_url, is_active) VALUES ('C++ Core', 'Learn object-oriented programming concepts with C++.', 4800, '3 Months', 'intermediate', 'programming', 'https://images.unsplash.com/photo-1581090700227-4c4f50b6b3d3', true);
INSERT INTO public.courses (title, description, price, duration, level, category, image_url, is_active) VALUES ('MySQL', 'Learn relational databases and SQL queries with MySQL.', 4800, '3 Months', 'beginner', 'database', 'https://images.unsplash.com/photo-1517433456452-f9633a875f6f', true);
INSERT INTO public.courses (title, description, price, duration, level, category, image_url, is_active) VALUES ('PHP', 'Master PHP programming for dynamic website development.', 4800, '3 Months', 'beginner', 'web', 'https://images.unsplash.com/photo-1590608897129-79da98d159e9', true);
INSERT INTO public.courses (title, description, price, duration, level, category, image_url, is_active) VALUES ('Data Structure & Algo - C & C++', 'Learn essential data structures and algorithms using C/C++.', 5800, '4 Months', 'intermediate', 'programming', 'https://images.unsplash.com/photo-1504639725590-34d0984388bd', true);
INSERT INTO public.courses (title, description, price, duration, level, category, image_url, is_active) VALUES ('Data Structure & Algo - Java', 'Understand data structures and algorithms using Java.', 5800, '4 Months', 'intermediate', 'programming', 'https://images.unsplash.com/photo-1526378722484-c1f0a04c1d9d', true);
INSERT INTO public.courses (title, description, price, duration, level, category, image_url, is_active) VALUES ('Django Python', 'Build powerful web applications with Django and Python.', 5800, '4 Months', 'intermediate', 'web', 'https://images.unsplash.com/photo-1584697964364-5b99d2a4160d', true);
INSERT INTO public.courses (title, description, price, duration, level, category, image_url, is_active) VALUES ('Spring Boot Java', 'Learn backend development with Java Spring Boot framework.', 5800, '4 Months', 'intermediate', 'web', 'https://images.unsplash.com/photo-1555066931-4365d14bab8c', true);
INSERT INTO public.courses (title, description, price, duration, level, category, image_url, is_active) VALUES ('Java Advance', 'Deep dive into advanced Java concepts and frameworks.', 5800, '4 Months', 'advanced', 'programming', 'https://images.unsplash.com/photo-1618477461857-9ed94c1c4a7a', true);
INSERT INTO public.courses (title, description, price, duration, level, category, image_url, is_active) VALUES ('Python Advance', 'Master advanced Python features for real-world projects.', 5800, '4 Months', 'advanced', 'programming', 'https://images.unsplash.com/photo-1581091870622-7c24b2d37e1d', true);
INSERT INTO public.courses (title, description, price, duration, level, category, image_url, is_active) VALUES ('C++ Advance', 'Advanced concepts in C++ for efficient programming.', 5800, '4 Months', 'advanced', 'programming', 'https://images.unsplash.com/photo-1580894894513-75834d77f7b6', true);
INSERT INTO public.courses (title, description, price, duration, level, category, image_url, is_active) VALUES ('Data Science', 'Analyze and visualize data using modern tools.', 9800, '6 Months', 'beginner', 'data', 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb', true);
INSERT INTO public.courses (title, description, price, duration, level, category, image_url, is_active) VALUES ('Tally Basic', 'Learn accounting fundamentals with Tally software.', 6000, '3 Months', 'beginner', 'finance', 'https://images.unsplash.com/photo-1588776814546-ec9f6b5af618', true);
INSERT INTO public.courses (title, description, price, duration, level, category, image_url, is_active) VALUES ('Tally Advance + GST', 'Advanced Tally skills with GST compliance.', 6800, '4 Months', 'advanced', 'finance', 'https://images.unsplash.com/photo-1631865813044-628a6e6c7f2c', true);
INSERT INTO public.courses (title, description, price, duration, level, category, image_url, is_active) VALUES ('Excel Basic', 'Get started with Excel for data entry and calculations.', 2000, '2 Months', 'beginner', 'productivity', 'https://images.unsplash.com/photo-1554224155-6726b3ff858f', true);
INSERT INTO public.courses (title, description, price, duration, level, category, image_url, is_active) VALUES ('Excel Advance', 'Master advanced Excel features for data analysis.', 3200, '3 Months', 'advanced', 'productivity', 'https://images.unsplash.com/photo-1551288049-bebda4e38f71', true);
INSERT INTO public.courses (title, description, price, duration, level, category, image_url, is_active) VALUES ('Scratch Programming', 'Learn block-based programming using Scratch, designed for kids.', 6800, '3 Months', 'beginner', 'kids', 'https://images.unsplash.com/photo-1627556704302-624fc54c53a6', true);
INSERT INTO public.courses (title, description, price, duration, level, category, image_url, is_active) VALUES ('AutoCAD', 'Learn 2D and 3D design using AutoCAD software.', 6800, '3 Months', 'beginner', 'design', 'https://images.unsplash.com/photo-1624953587687-df6a1f1f2e8b', true);
INSERT INTO public.courses (title, description, price, duration, level, category, image_url, is_active) VALUES ('Computer Hardware', 'Understand computer hardware, assembly, and troubleshooting.', 7800, '3 Months', 'beginner', 'hardware', 'https://images.unsplash.com/photo-1581090700020-2d87919b1d5d', true);
INSERT INTO public.courses (title, description, price, duration, level, category, image_url, is_active) VALUES ('Robotics for Age (8-14)', 'Introduce young minds to robotics and STEM concepts.', 11800, '3 Months', 'beginner', 'robotics', 'https://images.unsplash.com/photo-1581090700227-4c4f50b6b3d3', true);
INSERT INTO public.courses (title, description, price, duration, level, category, image_url, is_active) VALUES ('Robotics for Age (14+)', 'Learn advanced robotics with hardware and coding.', 19800, '5 Months', 'intermediate', 'robotics', 'https://images.unsplash.com/photo-1581091215367-59ab6a7c9f1d', true);
INSERT INTO public.courses (title, description, price, duration, level, category, image_url, is_active) VALUES ('CCC', 'Course on Computer Concepts – a basic government-certified IT course.', 8000, '5 Months', 'intermediate', 'computer', 'https://images.unsplash.com/photo-1547658719-da2b51169166', true);
INSERT INTO public.courses (title, description, price, duration, level, category, image_url, is_active) VALUES ('O-Level', 'Government recognized IT certification with in-depth computer concepts.', 12000, '12 Months', 'beginner', 'computer', 'https://images.unsplash.com/photo-1519389950473-47ba0277781c', true);